/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package G3_Inmuebles.vistasGrpo3.GestionInmuebles.InterfazInmueble;

import java.awt.Color;

/**
 *
 * @author dopar
 */
public class Modulossss extends javax.swing.JFrame {

    /**
     * Creates new form Modulossss
     */
    public Modulossss() {
        initComponents();
        //this.setUndecorated(true);
        this.setLocationRelativeTo(null);
        setResizable(false);//no miximizar
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedorPaneles = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        panelLetraModulos = new javax.swing.JPanel();
        letraModulo = new javax.swing.JLabel();
        panelLetraAdminInmuebles = new javax.swing.JPanel();
        letraAdminInmuebles = new javax.swing.JLabel();
        panelLetraReserAgenda = new javax.swing.JPanel();
        letraReserAgenda = new javax.swing.JLabel();
        panelLetraCatalogo = new javax.swing.JPanel();
        letraCatalogo = new javax.swing.JLabel();
        panelLetraNotiRecordatorio = new javax.swing.JPanel();
        letraNotiRecordatorio = new javax.swing.JLabel();
        panelLetraGestionPropiedad = new javax.swing.JPanel();
        letraGestionPropiedad = new javax.swing.JLabel();
        panelLetraReportes = new javax.swing.JPanel();
        letraReportes = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        panelAdminInmuebles = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        textObsAdicionales1 = new javax.swing.JTextField();
        botonEliminarAIG1 = new javax.swing.JButton();
        botonAgregarAIGes1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        textCedulaArrendatario1 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaGestionReserva1 = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        comboBoxDiaSGR1 = new javax.swing.JComboBox<>();
        textNombreArrendatario1 = new javax.swing.JTextField();
        comboBoxMesSGR1 = new javax.swing.JComboBox<>();
        textUnidadReserva1 = new javax.swing.JTextField();
        comboBoxAñoSGR1 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tablaVisualizacionUsuarioGestionUnidades1 = new javax.swing.JTable();
        comboBoxVisualizacionUsuarioGestionUnidades2 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        panelReserAgenda = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        comboBoxDiaReservaAgenda = new javax.swing.JComboBox<>();
        comboBoxMesReservaAgenda = new javax.swing.JComboBox<>();
        comboBoxAñoReservaAgenda = new javax.swing.JComboBox<>();
        panelCatalogo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCatalogo = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        comboBoxBuscarTipoCondominio = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        botonAgregarCatalogo = new javax.swing.JToggleButton();
        botonEditarCatalogo = new javax.swing.JToggleButton();
        botonEliminarCatalogo = new javax.swing.JToggleButton();
        panelNotiRecordatorio = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        comboBoxVisualizacionUsuarioGestionUnidades1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        panelGestPropiedad = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        panelReportes = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenedorPaneles.setBackground(new java.awt.Color(231, 222, 211));

        logo1.setIcon(new javax.swing.ImageIcon("D:\\Joel\\Documentos\\NetBeansProjects\\ProyectoFinalDiseno2023\\src\\view\\vistasGrpo3\\GestionInmuebles\\Imagenes\\logo.png")); // NOI18N

        panelLetraModulos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelLetraModulosMouseMoved(evt);
            }
        });
        panelLetraModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLetraModulosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLetraModulosMouseExited(evt);
            }
        });

        letraModulo.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        letraModulo.setText("MODULOS");

        javax.swing.GroupLayout panelLetraModulosLayout = new javax.swing.GroupLayout(panelLetraModulos);
        panelLetraModulos.setLayout(panelLetraModulosLayout);
        panelLetraModulosLayout.setHorizontalGroup(
            panelLetraModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLetraModulosLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(letraModulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLetraModulosLayout.setVerticalGroup(
            panelLetraModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLetraModulosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(letraModulo)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelLetraAdminInmuebles.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelLetraAdminInmueblesMouseMoved(evt);
            }
        });
        panelLetraAdminInmuebles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLetraAdminInmueblesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLetraAdminInmueblesMouseExited(evt);
            }
        });

        letraAdminInmuebles.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        letraAdminInmuebles.setText("Administrador de Inmuebles");
        letraAdminInmuebles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelLetraAdminInmueblesLayout = new javax.swing.GroupLayout(panelLetraAdminInmuebles);
        panelLetraAdminInmuebles.setLayout(panelLetraAdminInmueblesLayout);
        panelLetraAdminInmueblesLayout.setHorizontalGroup(
            panelLetraAdminInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLetraAdminInmueblesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(letraAdminInmuebles)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLetraAdminInmueblesLayout.setVerticalGroup(
            panelLetraAdminInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLetraAdminInmueblesLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(letraAdminInmuebles)
                .addGap(16, 16, 16))
        );

        panelLetraReserAgenda.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelLetraReserAgendaMouseMoved(evt);
            }
        });
        panelLetraReserAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLetraReserAgendaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLetraReserAgendaMouseExited(evt);
            }
        });

        letraReserAgenda.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        letraReserAgenda.setText("Reserva y agenda");

        javax.swing.GroupLayout panelLetraReserAgendaLayout = new javax.swing.GroupLayout(panelLetraReserAgenda);
        panelLetraReserAgenda.setLayout(panelLetraReserAgendaLayout);
        panelLetraReserAgendaLayout.setHorizontalGroup(
            panelLetraReserAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLetraReserAgendaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(letraReserAgenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLetraReserAgendaLayout.setVerticalGroup(
            panelLetraReserAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLetraReserAgendaLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(letraReserAgenda)
                .addGap(15, 15, 15))
        );

        panelLetraCatalogo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelLetraCatalogoMouseMoved(evt);
            }
        });
        panelLetraCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLetraCatalogoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLetraCatalogoMouseExited(evt);
            }
        });

        letraCatalogo.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        letraCatalogo.setText("Catalogo");

        javax.swing.GroupLayout panelLetraCatalogoLayout = new javax.swing.GroupLayout(panelLetraCatalogo);
        panelLetraCatalogo.setLayout(panelLetraCatalogoLayout);
        panelLetraCatalogoLayout.setHorizontalGroup(
            panelLetraCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLetraCatalogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(letraCatalogo)
                .addGap(85, 85, 85))
        );
        panelLetraCatalogoLayout.setVerticalGroup(
            panelLetraCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLetraCatalogoLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(letraCatalogo)
                .addGap(16, 16, 16))
        );

        panelLetraNotiRecordatorio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelLetraNotiRecordatorioMouseMoved(evt);
            }
        });
        panelLetraNotiRecordatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLetraNotiRecordatorioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLetraNotiRecordatorioMouseExited(evt);
            }
        });

        letraNotiRecordatorio.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        letraNotiRecordatorio.setText("Notificacion y Recordatorio");
        letraNotiRecordatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        letraNotiRecordatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelLetraNotiRecordatorioLayout = new javax.swing.GroupLayout(panelLetraNotiRecordatorio);
        panelLetraNotiRecordatorio.setLayout(panelLetraNotiRecordatorioLayout);
        panelLetraNotiRecordatorioLayout.setHorizontalGroup(
            panelLetraNotiRecordatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLetraNotiRecordatorioLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(letraNotiRecordatorio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLetraNotiRecordatorioLayout.setVerticalGroup(
            panelLetraNotiRecordatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLetraNotiRecordatorioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(letraNotiRecordatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        panelLetraGestionPropiedad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelLetraGestionPropiedadMouseMoved(evt);
            }
        });
        panelLetraGestionPropiedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLetraGestionPropiedadMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLetraGestionPropiedadMouseExited(evt);
            }
        });

        letraGestionPropiedad.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        letraGestionPropiedad.setText("Gestión Propiedad");

        javax.swing.GroupLayout panelLetraGestionPropiedadLayout = new javax.swing.GroupLayout(panelLetraGestionPropiedad);
        panelLetraGestionPropiedad.setLayout(panelLetraGestionPropiedadLayout);
        panelLetraGestionPropiedadLayout.setHorizontalGroup(
            panelLetraGestionPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLetraGestionPropiedadLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(letraGestionPropiedad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLetraGestionPropiedadLayout.setVerticalGroup(
            panelLetraGestionPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLetraGestionPropiedadLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(letraGestionPropiedad)
                .addGap(17, 17, 17))
        );

        panelLetraReportes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelLetraReportesMouseMoved(evt);
            }
        });
        panelLetraReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLetraReportesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLetraReportesMouseExited(evt);
            }
        });

        letraReportes.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        letraReportes.setText("Reportes");

        javax.swing.GroupLayout panelLetraReportesLayout = new javax.swing.GroupLayout(panelLetraReportes);
        panelLetraReportes.setLayout(panelLetraReportesLayout);
        panelLetraReportesLayout.setHorizontalGroup(
            panelLetraReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLetraReportesLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(letraReportes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLetraReportesLayout.setVerticalGroup(
            panelLetraReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLetraReportesLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(letraReportes)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout panelContenedorPanelesLayout = new javax.swing.GroupLayout(panelContenedorPaneles);
        panelContenedorPaneles.setLayout(panelContenedorPanelesLayout);
        panelContenedorPanelesLayout.setHorizontalGroup(
            panelContenedorPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLetraModulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLetraAdminInmuebles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLetraReserAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLetraCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLetraNotiRecordatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLetraGestionPropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLetraReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelContenedorPanelesLayout.setVerticalGroup(
            panelContenedorPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorPanelesLayout.createSequentialGroup()
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(panelLetraModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLetraAdminInmuebles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLetraReserAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLetraCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLetraNotiRecordatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLetraGestionPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLetraReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        getContentPane().add(panelContenedorPaneles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 654));

        logo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo2.setIcon(new javax.swing.ImageIcon("D:\\Joel\\Documentos\\NetBeansProjects\\ProyectoFinalDiseno2023\\src\\view\\vistasGrpo3\\GestionInmuebles\\Imagenes\\logo2.png")); // NOI18N
        logo2.setToolTipText("");
        getContentPane().add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1010, 120));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel12.setText("GESTION DE INMUEBLES");

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel13.setText("NUMEROS DE INMUBLES: ");

        jScrollPane5.setViewportView(jTextPane1);

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Joel\\Documentos\\NetBeansProjects\\ProyectoFinalDiseno2023\\src\\view\\vistasGrpo3\\GestionInmuebles\\Imagenes\\logoModulo.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        botonEliminarAIG1.setText("Eliminar");

        botonAgregarAIGes1.setText("Agregar");

        jLabel28.setText("Nombre del arrendatario");

        jLabel29.setText("Fecha de arrendatario");

        jLabel30.setText("Unidad a reservar");

        jLabel31.setText("Observaciones adicionales");

        jLabel32.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel32.setText("SISTEMA DE GESTIÓN DE RESERVAS");

        tablaGestionReserva1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tablaGestionReserva1);

        jLabel33.setText("Cédula del arrendatario");

        comboBoxDiaSGR1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        textNombreArrendatario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreArrendatario1ActionPerformed(evt);
            }
        });

        comboBoxMesSGR1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        comboBoxAñoSGR1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel33))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textCedulaArrendatario1)
                            .addComponent(textNombreArrendatario1)
                            .addComponent(textUnidadReserva1)
                            .addComponent(textObsAdicionales1)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(comboBoxDiaSGR1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxMesSGR1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxAñoSGR1, 0, 71, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(botonAgregarAIGes1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminarAIG1)
                .addGap(196, 196, 196))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCedulaArrendatario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombreArrendatario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(comboBoxDiaSGR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxMesSGR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxAñoSGR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textUnidadReserva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textObsAdicionales1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addGap(38, 38, 38)
                        .addComponent(botonAgregarAIGes1)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarAIG1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane4.addTab("Gestión", jPanel7);

        tablaVisualizacionUsuarioGestionUnidades1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tablaVisualizacionUsuarioGestionUnidades1);

        comboBoxVisualizacionUsuarioGestionUnidades2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidades existentes", "Información de la unidad", "Usuarios asignados", "Áreas comunes", " " }));
        comboBoxVisualizacionUsuarioGestionUnidades2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVisualizacionUsuarioGestionUnidades2ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel34.setText("INTERFAZ DE USUARIO DE GESTION DE UNIDADES");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxVisualizacionUsuarioGestionUnidades2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel34)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(comboBoxVisualizacionUsuarioGestionUnidades2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jTabbedPane4.addTab("Visualización", jPanel8);

        javax.swing.GroupLayout panelAdminInmueblesLayout = new javax.swing.GroupLayout(panelAdminInmuebles);
        panelAdminInmuebles.setLayout(panelAdminInmueblesLayout);
        panelAdminInmueblesLayout.setHorizontalGroup(
            panelAdminInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminInmueblesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelAdminInmueblesLayout.setVerticalGroup(
            panelAdminInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminInmueblesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", panelAdminInmuebles);

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel8.setText("AGENDA DE RESERVA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel9.setText("Ingrese la fecha: ");

        comboBoxDiaReservaAgenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        comboBoxMesReservaAgenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        comboBoxAñoReservaAgenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        javax.swing.GroupLayout panelReserAgendaLayout = new javax.swing.GroupLayout(panelReserAgenda);
        panelReserAgenda.setLayout(panelReserAgendaLayout);
        panelReserAgendaLayout.setHorizontalGroup(
            panelReserAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReserAgendaLayout.createSequentialGroup()
                .addGroup(panelReserAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReserAgendaLayout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabel8))
                    .addGroup(panelReserAgendaLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelReserAgendaLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxDiaReservaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxMesReservaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxAñoReservaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        panelReserAgendaLayout.setVerticalGroup(
            panelReserAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReserAgendaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(panelReserAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboBoxDiaReservaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMesReservaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxAñoReservaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("tab3", panelReserAgenda);

        tablaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaCatalogo);

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel10.setText("CATALOGO DE CONDOMINIOS");

        comboBoxBuscarTipoCondominio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dimensiones", "Numero habitaciones", "Áreas comunes", "Servicios", "Normas", " " }));

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel11.setText("Buscar tipo condominio");

        botonAgregarCatalogo.setText("Agregar");

        botonEditarCatalogo.setText("Editar");

        botonEliminarCatalogo.setText("Eliminar");

        javax.swing.GroupLayout panelCatalogoLayout = new javax.swing.GroupLayout(panelCatalogo);
        panelCatalogo.setLayout(panelCatalogoLayout);
        panelCatalogoLayout.setHorizontalGroup(
            panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCatalogoLayout.createSequentialGroup()
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jLabel10))
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxBuscarTipoCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(botonAgregarCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEditarCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        panelCatalogoLayout.setVerticalGroup(
            panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCatalogoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxBuscarTipoCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarCatalogo)
                    .addComponent(botonEditarCatalogo)
                    .addComponent(botonEliminarCatalogo))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("tab4", panelCatalogo);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Inmueble", "Tipo de evento", "Razón"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable2);

        comboBoxVisualizacionUsuarioGestionUnidades1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidades existentes", "Información de la unidad", "Usuarios asignados", "Áreas comunes", " " }));
        comboBoxVisualizacionUsuarioGestionUnidades1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVisualizacionUsuarioGestionUnidades1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Seleccionar inmueble:");

        jLabel15.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel15.setText("Notificaciones y recordatorios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(143, 143, 143))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboBoxVisualizacionUsuarioGestionUnidades1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(331, 331, 331))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxVisualizacionUsuarioGestionUnidades1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Visualizar Notificaciones", jPanel1);

        jLabel18.setText("Tipo de evento:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setText("Razón de notificación:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Seleccionar inmueble:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel17.setText("Nueva notificación");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel17)))
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(432, 432, 432))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton2)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Gestionar Notificaciones", jPanel3);

        javax.swing.GroupLayout panelNotiRecordatorioLayout = new javax.swing.GroupLayout(panelNotiRecordatorio);
        panelNotiRecordatorio.setLayout(panelNotiRecordatorioLayout);
        panelNotiRecordatorioLayout.setHorizontalGroup(
            panelNotiRecordatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotiRecordatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        panelNotiRecordatorioLayout.setVerticalGroup(
            panelNotiRecordatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotiRecordatorioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", panelNotiRecordatorio);

        jLabel21.setText("Seleccionar Propietario:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton1.setText("Habilitar Edición");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Edificio", "Casas", "Parcelas", "Terrenos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable3);

        jLabel22.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel22.setText("Gestión de propiedades");

        javax.swing.GroupLayout panelGestPropiedadLayout = new javax.swing.GroupLayout(panelGestPropiedad);
        panelGestPropiedad.setLayout(panelGestPropiedadLayout);
        panelGestPropiedadLayout.setHorizontalGroup(
            panelGestPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestPropiedadLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(panelGestPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestPropiedadLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(439, 439, 439))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestPropiedadLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestPropiedadLayout.createSequentialGroup()
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(195, 195, 195)))))
            .addGroup(panelGestPropiedadLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGestPropiedadLayout.setVerticalGroup(
            panelGestPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestPropiedadLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(panelGestPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab6", panelGestPropiedad);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Inmueble", "Cambio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable4);

        jLabel23.setText("Buscar inmueble:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel24.setText("Reportes");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jLabel24)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Visualizar reportes", jPanel4);

        jButton3.setText("Subir Reporte");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel26.setText("Seleccionar inmueble:");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel27.setText("Detallar el cambio:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel25.setText("Nuevo reporte");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(2, 2, 2)))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Gestionar Reportes", jPanel5);

        javax.swing.GroupLayout panelReportesLayout = new javax.swing.GroupLayout(panelReportes);
        panelReportes.setLayout(panelReportesLayout);
        panelReportesLayout.setHorizontalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelReportesLayout.setVerticalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab7", panelReportes);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 1010, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelLetraAdminInmueblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraAdminInmueblesMouseClicked
        // TODO add your handling code here:
        
       //panelLetraAdminInmuebles.setBackground(new Color(231,222,211));
       jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_panelLetraAdminInmueblesMouseClicked

    private void panelLetraModulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraModulosMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        //jPanel2.setBackground(Color.red);
    }//GEN-LAST:event_panelLetraModulosMouseClicked

    private void panelLetraReserAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraReserAgendaMouseClicked
        
        jTabbedPane1.setSelectedIndex(2);
        
    }//GEN-LAST:event_panelLetraReserAgendaMouseClicked

    private void panelLetraCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraCatalogoMouseClicked
        
        jTabbedPane1.setSelectedIndex(3);
        
    }//GEN-LAST:event_panelLetraCatalogoMouseClicked

    private void panelLetraNotiRecordatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraNotiRecordatorioMouseClicked
        
        jTabbedPane1.setSelectedIndex(4);
        
    }//GEN-LAST:event_panelLetraNotiRecordatorioMouseClicked

    private void panelLetraGestionPropiedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraGestionPropiedadMouseClicked
        
        jTabbedPane1.setSelectedIndex(5);
        
    }//GEN-LAST:event_panelLetraGestionPropiedadMouseClicked

    private void panelLetraReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraReportesMouseClicked
       
        jTabbedPane1.setSelectedIndex(6);
        
    }//GEN-LAST:event_panelLetraReportesMouseClicked

    private void panelLetraModulosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraModulosMouseMoved
       
        panelLetraModulos.setBackground(new Color(214, 180, 248));
        
    }//GEN-LAST:event_panelLetraModulosMouseMoved

    private void panelLetraAdminInmueblesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraAdminInmueblesMouseMoved
       
        panelLetraAdminInmuebles.setBackground(new Color(214, 180, 248));
        
    }//GEN-LAST:event_panelLetraAdminInmueblesMouseMoved

    private void panelLetraReserAgendaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraReserAgendaMouseMoved
        
        panelLetraReserAgenda.setBackground(new Color(214, 180, 248));
        
    }//GEN-LAST:event_panelLetraReserAgendaMouseMoved

    private void panelLetraCatalogoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraCatalogoMouseMoved
        
        panelLetraCatalogo.setBackground(new Color(214, 180, 248));
        
    }//GEN-LAST:event_panelLetraCatalogoMouseMoved

    private void panelLetraNotiRecordatorioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraNotiRecordatorioMouseMoved
        
        panelLetraNotiRecordatorio.setBackground(new Color(214, 180, 248));
        
    }//GEN-LAST:event_panelLetraNotiRecordatorioMouseMoved

    private void panelLetraGestionPropiedadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraGestionPropiedadMouseMoved
        
        panelLetraGestionPropiedad.setBackground(new Color(214, 180, 248));
        
    }//GEN-LAST:event_panelLetraGestionPropiedadMouseMoved

    private void panelLetraReportesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraReportesMouseMoved
       
        panelLetraReportes.setBackground(new Color(214, 180, 248));
        
    }//GEN-LAST:event_panelLetraReportesMouseMoved

    private void panelLetraModulosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraModulosMouseExited
        
        panelLetraModulos.setBackground(new Color(242, 242, 242));
        
    }//GEN-LAST:event_panelLetraModulosMouseExited

    private void panelLetraAdminInmueblesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraAdminInmueblesMouseExited
        
        panelLetraAdminInmuebles.setBackground(new Color(242, 242, 242));
        
    }//GEN-LAST:event_panelLetraAdminInmueblesMouseExited

    private void panelLetraReserAgendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraReserAgendaMouseExited
        
        panelLetraReserAgenda.setBackground(new Color(242, 242, 242));
        
    }//GEN-LAST:event_panelLetraReserAgendaMouseExited

    private void panelLetraCatalogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraCatalogoMouseExited
        
        panelLetraCatalogo.setBackground(new Color(242, 242, 242));
        
    }//GEN-LAST:event_panelLetraCatalogoMouseExited

    private void panelLetraNotiRecordatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraNotiRecordatorioMouseExited
        
        panelLetraNotiRecordatorio.setBackground(new Color(242, 242, 242));
        
    }//GEN-LAST:event_panelLetraNotiRecordatorioMouseExited

    private void panelLetraGestionPropiedadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraGestionPropiedadMouseExited
        
        panelLetraGestionPropiedad.setBackground(new Color(242, 242, 242));
        
    }//GEN-LAST:event_panelLetraGestionPropiedadMouseExited

    private void panelLetraReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLetraReportesMouseExited
        
        panelLetraReportes.setBackground(new Color(242, 242, 242));
        
    }//GEN-LAST:event_panelLetraReportesMouseExited

    private void comboBoxVisualizacionUsuarioGestionUnidades2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVisualizacionUsuarioGestionUnidades2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxVisualizacionUsuarioGestionUnidades2ActionPerformed

    private void textNombreArrendatario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreArrendatario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreArrendatario1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void comboBoxVisualizacionUsuarioGestionUnidades1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVisualizacionUsuarioGestionUnidades1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxVisualizacionUsuarioGestionUnidades1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulossss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulossss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulossss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulossss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulossss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarAIGes1;
    private javax.swing.JToggleButton botonAgregarCatalogo;
    private javax.swing.JToggleButton botonEditarCatalogo;
    private javax.swing.JButton botonEliminarAIG1;
    private javax.swing.JToggleButton botonEliminarCatalogo;
    private javax.swing.JComboBox<String> comboBoxAñoReservaAgenda;
    private javax.swing.JComboBox<String> comboBoxAñoSGR1;
    private javax.swing.JComboBox<String> comboBoxBuscarTipoCondominio;
    private javax.swing.JComboBox<String> comboBoxDiaReservaAgenda;
    private javax.swing.JComboBox<String> comboBoxDiaSGR1;
    private javax.swing.JComboBox<String> comboBoxMesReservaAgenda;
    private javax.swing.JComboBox<String> comboBoxMesSGR1;
    private javax.swing.JComboBox<String> comboBoxVisualizacionUsuarioGestionUnidades1;
    private javax.swing.JComboBox<String> comboBoxVisualizacionUsuarioGestionUnidades2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel letraAdminInmuebles;
    private javax.swing.JLabel letraCatalogo;
    private javax.swing.JLabel letraGestionPropiedad;
    private javax.swing.JLabel letraModulo;
    private javax.swing.JLabel letraNotiRecordatorio;
    private javax.swing.JLabel letraReportes;
    private javax.swing.JLabel letraReserAgenda;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JPanel panelAdminInmuebles;
    private javax.swing.JPanel panelCatalogo;
    private javax.swing.JPanel panelContenedorPaneles;
    private javax.swing.JPanel panelGestPropiedad;
    private javax.swing.JPanel panelLetraAdminInmuebles;
    private javax.swing.JPanel panelLetraCatalogo;
    private javax.swing.JPanel panelLetraGestionPropiedad;
    private javax.swing.JPanel panelLetraModulos;
    private javax.swing.JPanel panelLetraNotiRecordatorio;
    private javax.swing.JPanel panelLetraReportes;
    private javax.swing.JPanel panelLetraReserAgenda;
    private javax.swing.JPanel panelNotiRecordatorio;
    private javax.swing.JPanel panelReportes;
    private javax.swing.JPanel panelReserAgenda;
    private javax.swing.JTable tablaCatalogo;
    private javax.swing.JTable tablaGestionReserva1;
    private javax.swing.JTable tablaVisualizacionUsuarioGestionUnidades1;
    private javax.swing.JTextField textCedulaArrendatario1;
    private javax.swing.JTextField textNombreArrendatario1;
    private javax.swing.JTextField textObsAdicionales1;
    private javax.swing.JTextField textUnidadReserva1;
    // End of variables declaration//GEN-END:variables
}
