package G2_Usuarios;

import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author JoisH
 */
public class RegistroUsuario extends javax.swing.JFrame {



    public RegistroUsuario() {

        initComponents();
        setLocationRelativeTo(null);
        jLabel1.putClientProperty( "FlatLaf.styleClass", "h0" );

        setResizable(false);//no miximizar

        //mensajes
        jLNC.setVisible(false);
        jLNC1.setVisible(false);
        jLNC2.setVisible(false);
        jLNC3.setVisible(false);
        jLNC4.setVisible(false);
        jLNC5.setVisible(false);
        jLNC6.setVisible(false);


        //para no pedir ingrese el ping si ya esta lleno
        if (!jTPin1.getText().equals("")||!jTPin2.getText().equals("")
                ||!jTPin3.getText().equals("")
                ||!jTPin4.getText().equals("")
                ||!jTPin5.getText().equals("")
                ||!jTPin6.getText().equals("")
        ) {
            jLNC6.setVisible(false);
        }













        //parra regresar a la normalidad
        if(jTFContraseñaUsuario.equals("")){
            jLNC4.setText("*Por favor, ingresa una contraseña (12+carácteres especiales)");
            jLNC4.setForeground(java.awt.Color.orange);//color de letras
        }

        if(jTFContraseñaUsuario1.equals("")){
            jLNC5.setText("*Por favor, ingresa una contraseña (12+carácteres especiales)");
            jLNC5.setForeground(java.awt.Color.orange);//color de letras
        }
    }








    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFApeCUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTFNomCUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTFCIUsuario = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFContraseñaUsuario = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLNC = new javax.swing.JLabel();
        jLNC1 = new javax.swing.JLabel();
        jLNC2 = new javax.swing.JLabel();
        jLNC3 = new javax.swing.JLabel();
        jLNC4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTFContraseñaUsuario1 = new javax.swing.JPasswordField();
        jLNC5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLNC6 = new javax.swing.JLabel();
        jTPin1 = new javax.swing.JTextField();
        jTPin2 = new javax.swing.JTextField();
        jTPin3 = new javax.swing.JTextField();
        jTPin4 = new javax.swing.JTextField();
        jTPin5 = new javax.swing.JTextField();
        jTPin6 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
                jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
                jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombres Completos");
        jLabel3.setAutoscrolls(true);
        jLabel3.setDoubleBuffered(true);
        jLabel3.setFocusCycleRoot(true);
        jLabel3.setFocusTraversalPolicyProvider(true);

        jTFApeCUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jTFApeCUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTFApeCUsuario.setBorder(null);
        jTFApeCUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFApeCUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFApeCUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTFApeCUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTFApeCUsuarioMouseExited(evt);
            }
        });
        jTFApeCUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFApeCUsuarioActionPerformed(evt);
            }
        });
        jTFApeCUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFApeCUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFApeCUsuarioKeyTyped(evt);
            }
        });

        jSeparator1.setAutoscrolls(true);
        jSeparator1.setDoubleBuffered(true);
        jSeparator1.setFocusCycleRoot(true);
        jSeparator1.setFocusTraversalPolicyProvider(true);
        jSeparator1.setFocusable(true);
        jSeparator1.setInheritsPopupMenu(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellidos Completos");
        jLabel4.setAutoscrolls(true);
        jLabel4.setDoubleBuffered(true);
        jLabel4.setFocusCycleRoot(true);
        jLabel4.setFocusTraversalPolicyProvider(true);

        jTFNomCUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jTFNomCUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTFNomCUsuario.setBorder(null);
        jTFNomCUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFNomCUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFNomCUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTFNomCUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTFNomCUsuarioMouseExited(evt);
            }
        });
        jTFNomCUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomCUsuarioActionPerformed(evt);
            }
        });
        jTFNomCUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNomCUsuarioKeyPressed(evt);
            }
        });

        jSeparator2.setAutoscrolls(true);
        jSeparator2.setDoubleBuffered(true);
        jSeparator2.setFocusCycleRoot(true);
        jSeparator2.setFocusTraversalPolicyProvider(true);
        jSeparator2.setFocusable(true);
        jSeparator2.setInheritsPopupMenu(true);

        jTFCIUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jTFCIUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTFCIUsuario.setBorder(null);
        jTFCIUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFCIUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFCIUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTFCIUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTFCIUsuarioMouseExited(evt);
            }
        });
        jTFCIUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCIUsuarioActionPerformed(evt);
            }
        });
        jTFCIUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCIUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCIUsuarioKeyTyped(evt);
            }
        });

        jSeparator3.setAutoscrolls(true);
        jSeparator3.setDoubleBuffered(true);
        jSeparator3.setFocusCycleRoot(true);
        jSeparator3.setFocusTraversalPolicyProvider(true);
        jSeparator3.setFocusable(true);
        jSeparator3.setInheritsPopupMenu(true);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cédula de Identidad");
        jLabel6.setAutoscrolls(true);
        jLabel6.setDoubleBuffered(true);
        jLabel6.setFocusCycleRoot(true);
        jLabel6.setFocusTraversalPolicyProvider(true);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre de Usuario");
        jLabel7.setAutoscrolls(true);
        jLabel7.setDoubleBuffered(true);
        jLabel7.setFocusCycleRoot(true);
        jLabel7.setFocusTraversalPolicyProvider(true);

        jTFUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jTFUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTFUsuario.setBorder(null);
        jTFUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTFUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTFUsuarioMouseExited(evt);
            }
        });
        jTFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuarioActionPerformed(evt);
            }
        });
        jTFUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFUsuarioKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contraseña");
        jLabel8.setAutoscrolls(true);
        jLabel8.setDoubleBuffered(true);
        jLabel8.setFocusCycleRoot(true);
        jLabel8.setFocusTraversalPolicyProvider(true);

        jTFContraseñaUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jTFContraseñaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTFContraseñaUsuario.setBorder(null);
        jTFContraseñaUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFContraseñaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFContraseñaUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTFContraseñaUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTFContraseñaUsuarioMouseExited(evt);
            }
        });
        jTFContraseñaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFContraseñaUsuarioActionPerformed(evt);
            }
        });
        jTFContraseñaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFContraseñaUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFContraseñaUsuarioKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrate");

        jLNC.setForeground(new java.awt.Color(255, 102, 0));
        jLNC.setText("*Por favor, ingresa tus nombres completos");

        jLNC1.setForeground(new java.awt.Color(255, 102, 0));
        jLNC1.setText("*Por favor, ingresa tus apellidos completos");

        jLNC2.setForeground(new java.awt.Color(255, 102, 0));
        jLNC2.setText("*Por favor, ingresa tu cédula de identidad");

        jLNC3.setForeground(new java.awt.Color(255, 102, 0));
        jLNC3.setText("*Por favor, ingresa un nombre de usuario");

        jLNC4.setForeground(new java.awt.Color(255, 102, 0));
        jLNC4.setText("*Por favor, ingresa una contraseña (12+carácteres especiales)");

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar Usuario");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Aceptar los términos y condiciones");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Condiciones de Uso del Sistema \n\nBienvenido al Sistema. Al utilizar este sistema, aceptas las siguientes condiciones de uso. \nPor favor, lee detenidamente antes de continuar:\n\n1. Registro de Información: Al registrarte en este sistema, te comprometes a proporcionar información precisa y actualizada sobre tu empresa, clientes, proveedores y productos.\n2. Uso Apropiado: El sistema está destinado únicamente para llevar a cabo operaciones legales y comerciales relacionadas con la gestión de clientes, proveedores, productos, compras, ventas y facturación. \nQueda estrictamente prohibido utilizar este sistema para fines ilegales, fraudulentos o maliciosos.\n3. Protección de Datos: Reconoces y aceptas que la información proporcionada, incluidos los datos personales de clientes y proveedores, se manejará de acuerdo con las leyes de protección de datos personales. \nNos comprometemos a tomar medidas para proteger la confidencialidad y seguridad de los datos almacenados en el sistema.\n4. Mal Uso del Sistema: Cualquier intento de acceso no autorizado, manipulación de datos, interrupción del servicio o cualquier otro comportamiento malicioso será tratado con seriedad. \nNos reservamos el derecho de tomar medidas legales en caso de mal uso del sistema.\n5. Cumplimiento Legal: Al utilizar este sistema, te comprometes a cumplir con todas las leyes y regulaciones relevantes, incluidas las leyes fiscales y de protección de datos.\n6. Responsabilidad: No nos hacemos responsables por pérdidas, daños o perjuicios derivados del uso del sistema, incluidos errores en los datos, interrupciones del servicio o pérdida de información.\n7. Actualización de Términos: Nos reservamos el derecho de actualizar estas condiciones de uso en cualquier momento. \nTe recomendamos revisar periódicamente estas condiciones para estar al tanto de los cambios.\n\nAl continuar utilizando el Sistema de Registro y Facturación, aceptas cumplir con estas condiciones de uso.\nSi no estás de acuerdo con estas condiciones, por favor, no utilices el sistema.\n");
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        jTFContraseñaUsuario1.setBackground(new java.awt.Color(0, 0, 0));
        jTFContraseñaUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jTFContraseñaUsuario1.setBorder(null);
        jTFContraseñaUsuario1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFContraseñaUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFContraseñaUsuario1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTFContraseñaUsuario1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTFContraseñaUsuario1MouseExited(evt);
            }
        });
        jTFContraseñaUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFContraseñaUsuario1ActionPerformed(evt);
            }
        });
        jTFContraseñaUsuario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFContraseñaUsuario1KeyPressed(evt);
            }
        });

        jLNC5.setForeground(new java.awt.Color(255, 102, 0));
        jLNC5.setText("*Por favor, ingresa nuevamente la contraseña");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirmar Contraseña");
        jLabel9.setAutoscrolls(true);
        jLabel9.setDoubleBuffered(true);
        jLabel9.setFocusCycleRoot(true);
        jLabel9.setFocusTraversalPolicyProvider(true);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PIN ");
        jLabel10.setAutoscrolls(true);
        jLabel10.setDoubleBuffered(true);
        jLabel10.setFocusCycleRoot(true);
        jLabel10.setFocusTraversalPolicyProvider(true);

        jLNC6.setForeground(new java.awt.Color(255, 102, 0));
        jLNC6.setText("*Por favor, ingresa un PIN de seguridad");

        jTPin1.setBackground(new java.awt.Color(0, 0, 0));
        jTPin1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTPin1.setForeground(new java.awt.Color(255, 255, 255));
        jTPin1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTPin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTPin1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTPin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPin1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTPin1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTPin1MouseExited(evt);
            }
        });
        jTPin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPin1ActionPerformed(evt);
            }
        });
        jTPin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTPin1KeyTyped(evt);
            }
        });

        jTPin2.setBackground(new java.awt.Color(0, 0, 0));
        jTPin2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTPin2.setForeground(new java.awt.Color(255, 255, 255));
        jTPin2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTPin2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTPin2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTPin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPin2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTPin2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTPin2MouseExited(evt);
            }
        });
        jTPin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPin2ActionPerformed(evt);
            }
        });

        jTPin3.setBackground(new java.awt.Color(0, 0, 0));
        jTPin3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTPin3.setForeground(new java.awt.Color(255, 255, 255));
        jTPin3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTPin3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTPin3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTPin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPin3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTPin3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTPin3MouseExited(evt);
            }
        });
        jTPin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPin3ActionPerformed(evt);
            }
        });

        jTPin4.setBackground(new java.awt.Color(0, 0, 0));
        jTPin4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTPin4.setForeground(new java.awt.Color(255, 255, 255));
        jTPin4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTPin4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTPin4.setCaretColor(new java.awt.Color(255, 255, 255));
        jTPin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPin4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTPin4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTPin4MouseExited(evt);
            }
        });
        jTPin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPin4ActionPerformed(evt);
            }
        });

        jTPin5.setBackground(new java.awt.Color(0, 0, 0));
        jTPin5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTPin5.setForeground(new java.awt.Color(255, 255, 255));
        jTPin5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTPin5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTPin5.setCaretColor(new java.awt.Color(255, 255, 255));
        jTPin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPin5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTPin5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTPin5MouseExited(evt);
            }
        });
        jTPin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPin5ActionPerformed(evt);
            }
        });

        jTPin6.setBackground(new java.awt.Color(0, 0, 0));
        jTPin6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTPin6.setForeground(new java.awt.Color(255, 255, 255));
        jTPin6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTPin6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTPin6.setCaretColor(new java.awt.Color(255, 255, 255));
        jTPin6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPin6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTPin6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTPin6MouseExited(evt);
            }
        });
        jTPin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPin6ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("© Todos los Derechos Reservados.2023");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jTFNomCUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                                                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jTFApeCUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jTFCIUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jTPin1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTPin2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTPin3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLNC6)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jTPin4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTPin5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTPin6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLNC1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLNC2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLNC, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(2, 2, 2)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jTFContraseñaUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel9)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLNC5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel7)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLNC3))
                                                                .addComponent(jTFUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(jLNC4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(jTFContraseñaUsuario, javax.swing.GroupLayout.Alignment.LEADING))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(146, 146, 146)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(182, 182, 182)
                                                .addComponent(jLabel11)))
                                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLNC))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNomCUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLNC1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFApeCUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLNC2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCIUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                                        .addComponent(jLNC3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLNC6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTPin1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTPin2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTPin3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTPin4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTPin5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTPin6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLNC4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFContraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                        .addComponent(jLNC5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFContraseñaUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void jTPin5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin5MouseExited(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(false);
    }

    private void jTPin5MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin5MouseClicked(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(true);

    }

    private void jTPin4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin4MouseExited(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(false);
    }

    private void jTPin4MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin4MouseClicked(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(true);

    }

    private void jTPin3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin3MouseExited(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(false);
    }

    private void jTPin3MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin3MouseClicked(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(true);

    }

    private void jTPin2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin2MouseExited(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(false);
    }

    private void jTPin2MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin2MouseClicked(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(true);

    }

    private void jTPin1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin1MouseExited(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(false);
    }

    private void jTPin1MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin1MouseClicked(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(true);


    }

    private void jTFContraseñaUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTFContraseñaUsuario1MouseExited(java.awt.event.MouseEvent evt) {
        //

        jLNC5.setVisible(false);
    }

    private void jTFContraseñaUsuario1MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jTFContraseñaUsuario1MouseClicked(java.awt.event.MouseEvent evt) {
        jLNC5.setVisible(true);

    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {

    }

    private void jTFContraseñaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTFContraseñaUsuarioMouseExited(java.awt.event.MouseEvent evt) {
        setCursor(Cursor.getDefaultCursor());
        jLNC4.setVisible(false);
    }

    private void jTFContraseñaUsuarioMouseEntered(java.awt.event.MouseEvent evt) {

        setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
    }

    private void jTFContraseñaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
        //parra regresar a la normalidad
        if(jTFContraseñaUsuario.equals("")){
            jLNC4.setText("*Por favor, ingresa una contraseña (12+carácteres especiales)");
            jLNC4.setForeground(java.awt.Color.orange);//color de letras
        }


        jLNC4.setVisible(true);



    }

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTFUsuarioMouseExited(java.awt.event.MouseEvent evt) {
        jLNC3.setVisible(false);
    }

    private void jTFUsuarioMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jTFUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
        jLNC3.setVisible(true);

    }

    private void jTFCIUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTFCIUsuarioMouseExited(java.awt.event.MouseEvent evt) {
        jLNC2.setVisible(false);
    }

    private void jTFCIUsuarioMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jTFCIUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
        jLNC2.setVisible(true);
        if(jTFCIUsuario.equals("")){
            jLNC2.setText("**Por favor, ingresa tu cédula de identidad");
            jLNC2.setForeground(java.awt.Color.ORANGE);//color de letras
        }
    }

    private void jTFNomCUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTFNomCUsuarioMouseExited(java.awt.event.MouseEvent evt) {
        jLNC.setVisible(false);
    }

    private void jTFNomCUsuarioMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jTFNomCUsuarioMouseClicked(java.awt.event.MouseEvent evt) {

        jLNC.setVisible(true);


    }

    private void jTFApeCUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTFApeCUsuarioMouseExited(java.awt.event.MouseEvent evt) {
        setCursor(Cursor.getDefaultCursor());
        jLNC1.setVisible(false);
    }

    private void jTFApeCUsuarioMouseEntered(java.awt.event.MouseEvent evt) {
        setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
    }

    private void jTFApeCUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
        jLNC1.setVisible(true);


    }

    private void jTPin6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin6MouseExited(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(false);
    }

    private void jTPin6MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jTPin6MouseClicked(java.awt.event.MouseEvent evt) {
        jLNC6.setVisible(true);

    }

    private void jTPin1KeyTyped(java.awt.event.KeyEvent evt) {

    }

    private void jTFContraseñaUsuarioKeyPressed(java.awt.event.KeyEvent evt) {
        //parra regresar a la normalidad
        if(jTFContraseñaUsuario.equals("")){
            jLNC4.setText("*Por favor, ingresa una contraseña (12+carácteres especiales)");
            jLNC4.setForeground(java.awt.Color.orange);//color de letras
        }


    }

    private void jTFContraseñaUsuario1KeyPressed(java.awt.event.KeyEvent evt) {

        jTFContraseñaUsuario1.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isLetter(c) && c != '.'&& !Character.isDigit(c) && c != '-' && c != '*' && c != '/' && c != '_'  && c != 'ñ' && c != 'Ñ' ) {
                    Toolkit.getDefaultToolkit().beep(); // Emite un sonido de alerta
                    e.consume();
                }
            }


            public void keyPressed(KeyEvent e) {
                if (e.getKeyChar() == KeyEvent.VK_SPACE) {
                    Toolkit.getDefaultToolkit().beep(); // Emite un sonido de alerta
                    e.consume();
                }
            }
        });
    }

    private void jTFNomCUsuarioKeyPressed(java.awt.event.KeyEvent evt) {
        jTFNomCUsuario.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isLetter(c) && c != 'á' && c != 'é' && c != 'í' && c != 'ó' && c != 'ú' && c != 'Á' && c != 'É' && c != 'Í' && c != 'Ó' && c != 'Ú' && c != 'ñ' && c != 'Ñ' && c != ' ') {
                    Toolkit.getDefaultToolkit().beep(); // Emite un sonido de alerta
                    e.consume();
                }
            }
        });
    }

    private void jTFApeCUsuarioKeyTyped(java.awt.event.KeyEvent evt) {

    }

    private void jTFApeCUsuarioKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void jTFCIUsuarioKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void jTFContraseñaUsuarioKeyTyped(java.awt.event.KeyEvent evt) {
        //parra regresar a la normalidad
        if(jTFContraseñaUsuario.equals("")){
            jLNC4.setText("*Por favor, ingresa una contraseña (12+carácteres especiales)");
            jLNC4.setForeground(java.awt.Color.orange);//color de letras
        }
    }

    private void jTFUsuarioKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void jTFUsuarioKeyTyped(java.awt.event.KeyEvent evt) {
        jTFUsuario.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isLetter(c) && !Character.isDigit(c)  && c != 'ñ' && c != 'Ñ' && c != '_'&& c != '.'&&  c==' ') {
                    Toolkit.getDefaultToolkit().beep(); // Emite un sonido de alerta
                    e.consume();
                }
            }

            public void keyPressed(KeyEvent e) {
                if (e.getKeyChar() == KeyEvent.VK_SPACE) {
                    Toolkit.getDefaultToolkit().beep(); // Emite un sonido de alerta
                    e.consume();
                }
            }
        });
    }

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {

    }

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {

    }

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {

    }

    private void jTFCIUsuarioKeyTyped(java.awt.event.KeyEvent evt) {
        jTFCIUsuario.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    Toolkit.getDefaultToolkit().beep(); // Emite un sonido de alerta
                    e.consume();
                }
            }
        });        // TODO add your handling code here:
    }

















    public static void main(String args[]) {
        //Getting started--FlatLaf - Flat Look and Feel


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);

            }
        });
    }












    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLNC;
    private javax.swing.JLabel jLNC1;
    private javax.swing.JLabel jLNC2;
    private javax.swing.JLabel jLNC3;
    private javax.swing.JLabel jLNC4;
    private javax.swing.JLabel jLNC5;
    private javax.swing.JLabel jLNC6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTFApeCUsuario;
    private javax.swing.JTextField jTFCIUsuario;
    private javax.swing.JPasswordField jTFContraseñaUsuario;
    private javax.swing.JPasswordField jTFContraseñaUsuario1;
    private javax.swing.JTextField jTFNomCUsuario;
    private javax.swing.JTextField jTFUsuario;
    private javax.swing.JTextField jTPin1;
    private javax.swing.JTextField jTPin2;
    private javax.swing.JTextField jTPin3;
    private javax.swing.JTextField jTPin4;
    private javax.swing.JTextField jTPin5;
    private javax.swing.JTextField jTPin6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration
}